services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend/public:/opt/app/public"
    restart: always
    depends_on:
      - strapiDB
    networks:
      - web
      - strapi-app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always
    networks:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - traefik
    networks:
      - web
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dollarlaw.rule=Host(`dollarlaw.live`) || Host(`www.dollarlaw.live`)"
      - "traefik.http.routers.dollarlaw.entrypoints=websecure"
      - "traefik.http.routers.dollarlaw.tls=true"
      - "traefik.http.routers.dollarlaw.tls.certresolver=letencrypt"
      - "traefik.http.services.dollarlaw.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.1.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/traefik.yml:/traefik.yml:ro
      - traefik-certs:/certs
    networks:
      - proxy

volumes:
  traefik-certs:
    name: traefik-certs

networks:
  web:
  proxy:
